version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_sobrelamesa
    networks:
      - my-network
    ports:
      - "3305:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: back-slm
    depends_on:
      db:
        condition: service_healthy
    environment:
      MYSQL_HOST: db
      MYSQL_DB: db_sobrelamesa
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      DATABASE_URL: mysql://root:root@db:3306/db_sobrelamesa
    ports:
      - "3000:3000"
    networks:
      - my-network
    volumes:
      - ./back:/app
      - /app/node_modules

networks:
  my-network:
    driver: bridge